### ISSUE TITLE
Invalid dataset

### ISSUE THREAD

**Issue by vitiennam** [sipeed/Maix_Toolbox#1]
Hi,

I use mobilenet v1, train and then convert to kmodel but there is error:

Fatal: Invalid dataset.
System.ArgumentException: Invalid dataset.
   at NnCase.Converter.Data.Dataset..ctor(String path, IReadOnlyCollection`1 allowdExtensions, ReadOnlySpan`1 dimensions, Int32 batchSize, PostprocessMethods postprocessMethod, Nullable`1 mean, Nullable`1 std) in D:\Work\Repository\nncase\src\NnCase.Converter\Data\Dataset.cs:line 67
   at NnCase.Converter.Data.ImageDataset..ctor(String path, ReadOnlySpan`1 dimensions, Int32 batchSize, PreprocessMethods preprocessMethods, PostprocessMethods postprocessMethod, Nullable`1 mean, Nullable`1 std) in D:\Work\Repository\nncase\src\NnCase.Converter\Data\Dataset.cs:line 212
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 249
   at NnCase.Cli.Program.<Main>(String[] args)

link tflite model you can test: https://drive.google.com/open?id=1pqVAuQ9D4kptZGStNMR6vpXjS3h8j8kG
Thanks

**Comment by Ace95** [comment]
Following, I get the same error when I try to convert a tflite model to kmodel

**Comment by Ace95** [comment]
> Hi,
> 
> I use mobilenet v1, train and then convert to kmodel but there is error:
> 
> Fatal: Invalid dataset.
> System.ArgumentException: Invalid dataset.
> at NnCase.Converter.Data.Dataset..ctor(String path, IReadOnlyCollection`1 allowdExtensions, ReadOnlySpan`1 dimensions, Int32 batchSize, PostprocessMethods postprocessMethod, Nullable`1 mean, Nullable`1 std) in D:\Work\Repository\nncase\src\NnCase.Converter\Data\Dataset.cs:line 67
> at NnCase.Converter.Data.ImageDataset..ctor(String path, ReadOnlySpan`1 dimensions, Int32 batchSize, PreprocessMethods preprocessMethods, PostprocessMethods postprocessMethod, Nullable`1 mean, Nullable`1 std) in D:\Work\Repository\nncase\src\NnCase.Converter\Data\Dataset.cs:line 212
> at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 249
> at NnCase.Cli.Program.
> 
> (String[] args)
> link tflite model you can test: https://drive.google.com/open?id=1pqVAuQ9D4kptZGStNMR6vpXjS3h8j8kG
> Thanks

Put some images in the "images" folder, this should fix the problem. Remeber the more images you put the longer it will take to complete the conversion from the tflite model to the kmodel, but at the same time you should get better results.
